markdown: kramdown
style: davewhipp

plugins:
  - jekyll-scholar
  - jekyll-regex-replace

# Jekyll Scholar configuration for bibliography
scholar:
  style: science
  locale: en
  sort_by: year
  order: descending
  source: ./_bibliography
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [mathmode, subscript, smallcaps, superscript]
  replace_strings: true
  group_by: none